language: rust
rust:
  - nightly
  - stable

cache: cargo

script:
  - cargo test
  - cargo test --release
  - cargo build --examples --all
  - cargo build --examples --all --release

branches:
  only:
    - master
