environment:
  global:
    RUST_VERSION: stable
  matrix:
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

image: Visual Studio 2017

install:
    # setup rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

test_script:
  - cargo test
  - cargo test --release

skip_tags: true

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
